version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: taskpro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
